@startuml
'https://plantuml.com/class-diagram

class Inventory{
addInstrument()
search(GuitarSpec)
search(MandolinSpec)
}
abstract class Instrument{
- serialNumber: String
- price: double
}

class Guitar {

getSpec() : GuitarSpec
}

class Mandolin {

getSpec() : MandolinSpec
}

abstract class InstrumentSpec{
builder

}

class GuitarSpec{


}
enum Builder {
 AIRLINE
 KOLL
 BURNS
 CORT
 FENDER
}

enum Type {
CLASSICAL
ACOUSTIC
ELECTROACOUSTIC
ELECTRIC
FENDER
}

enum Wood {
ALDER
MAHOGANY
OAK;
}

Wood -[hidden]-Builder
Inventory o-- "0..*" Guitar:consists of
@enduml